### PR TITLE
Skip already allocated indices

### PR DESCRIPTION
**Pull request by ferki**
Currently it can take a long time to apply index allocation rules with curator if there are many indices (like >10 minutes for 4 weeks' worth of hourly indices). This patch adds a check to see if the index already has the allocation rule to be set, and if yes, it skips the index. It made the above example finish just under 9 seconds.

Feel free to ask for followup changes if required, and please indicate if signing the CLA is required for accepting this contribution.

### CODE REVIEW

**Comment by untergeek** [comment]
Thanks for making curator more awesome!  This looks great!

Yes, please sign the [CLA](http://www.elasticsearch.org/contributor-agreement/).

Once that's done:
- I will merge into the current master
- I will put your name into the contributors (if it's not already there).
- I will be reimplementing the method in my curator v3 branch in a way that makes sense there.

**Comment by ferki** [comment]
@untergeek: thanks for the quick feedback! I signed the CCLA and I'm already in the list of contributors ;)

**Comment by untergeek** [comment]
Hmmm.  Did you use @ferki as the username you signed with?  I'm still getting a "not signed" message.

**Comment by ferki** [comment]
@untergeek: yes, I used `ferki` as github username, and also my work email address/details to sign the CCLA. Then I received the email verification email, and then the final signed PDF document.

Let me know if there are any additional steps.

**Pull request merged**
